### ISSUE TITLE
Bug in stretched grid checkpoint global attributes TARGET_LAT and TARGET_LON

### ISSUE THREAD

**Issue by lizziel** [GEOS-ESM/MAPL#1977]
GCHP stretched grid runs using MAPL 2.26.0 crash when restarting using an output checkpoint file. The problem is the global attributes for `TARGET_LAT` and `TARGET_LON`. For example, I am running a simulation with the following settings in GCHP.rc:

```
GCHP.STRETCH_FACTOR: 4.0
GCHP.TARGET_LON: -64.0
GCHP.TARGET_LAT: 32.0
```

My initial restart file contains these global attributes:

```
// global attributes:
                :STRETCH_FACTOR = 4.f ;
                :TARGET_LAT = 32.f ;
                :TARGET_LON = -64.f ;
```

My output checkpoint file used to start the next run contains these:

```
// global attributes:
                :STRETCH_FACTOR = 4.f ;
                :TARGET_LAT = 0.5585054f ;
                :TARGET_LON = -1.117011f ;
```

The restarted run crashes with this error:

```
pe=00012 FAIL at line=06123    MAPL_Generic.F90                         <Factories not equal>
pe=00012 FAIL at line=01609    MAPL_Generic.F90                         <unknown error>
pe=00012 FAIL at line=01047    MAPL_Generic.F90                         <status=-1>
pe=00012 FAIL at line=01175    Chem_GridCompMod.F90                     <status=-1>
pe=00012 FAIL at line=01807    MAPL_Generic.F90                         <status=-1>
pe=00012 FAIL at line=00167    BaseProfiler.F90                         <Timer <GCHP> does not match start timer <GCHPchem>>
pe=00012 FAIL at line=01825    MAPL_Generic.F90                         <status=1>
pe=00012 FAIL at line=00655    MAPL_CapGridComp.F90                     <status=1>
pe=00012 FAIL at line=00959    MAPL_CapGridComp.F90                     <status=1>
pe=00012 FAIL at line=00299    MAPL_Cap.F90                             <status=1>
pe=00012 FAIL at line=00258    MAPL_Cap.F90                             <status=1>
pe=00012 FAIL at line=00192    MAPL_Cap.F90                             <status=1>
pe=00012 FAIL at line=00169    MAPL_Cap.F90                             <status=1>
pe=00012 FAIL at line=00031    GCHPctm.F90                              <status=1>
```

This issue was first reported in https://github.com/geoschem/GCHP/issues/287.

**Comment by mathomp4** [comment]
I thought we fixed this in https://github.com/GEOS-ESM/MAPL/pull/1736

Do you need the fix backported?

**Comment by mathomp4** [comment]
I just looked and I think the fix is in 2.28.0. Would you like it backported to 2.26.x?

**Comment by lizziel** [comment]
Perfect! This is much better than my quick fix which reads in the config file again at time of write. No need to backport. I'll cherry-pick the commit.

**Comment by lizziel** [comment]
@mathomp4, I tested the fix from https://github.com/GEOS-ESM/MAPL/pull/1736 and it still crashes. The new global attributes are slightly different from the original in the config file and thus there is a still a "Factories not equal" error.

```
// global attributes:
                :STRETCH_FACTOR = 4.f ;
                :TARGET_LAT = 31.9999997521163 ;
                :TARGET_LON = -63.9999995042325 ;
```

I implemented a quick fix in GCHP (see commit [here](https://github.com/geoschem/MAPL/commit/48ad6c9606e9016960a2b67ef802befc7080b55f)) but isn't very pretty.

**Comment by mathomp4** [comment]
@lizziel Aw nuts. Looks like fun with floating point math. My guess is we need to do some tolerance-based floating point comparisons in the "are two factories equal" code. I'll work with @tclune and @bena-nasa on this (mainly because I don't know where that code is 😄 )

When we get a possible fix, we'll reach out to you to try. I'm not sure we have a test for this, but maybe @bena-nasa can whip one up to add to our suite.

**Comment by lizziel** [comment]
Thanks @bena-nasa. I favor any solution that (1) keeps the RC input in degrees, and (2) preserves the target lat/lon global attribute values across runs, i.e. exactly the same in both input restart and output restart.

**Comment by bena-nasa** [comment]
@lizziel there's more going on here, turns out the cubed-sphere grid factory, the create a grid from a file is broken, it is not even reading back the stretching parameters at all for arcane reasons, I'll fix that first, nothings going to work if that is broken...

**Comment by bena-nasa** [comment]
Fixed this, PR coming in the AM
